### ISSUE TITLE
Problems running with version from master branch

### ISSUE THREAD

**Issue by r0b-** [angular/material-tools#24]
Hi,

I like to use the extending palettes feature so I installed the master version...
Unfortunately I'm getting this error:
```
>material-tools.cmd -c angular-material-config.json

module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/MaterialCLI'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\...\npm\node_modules\angular-material-tools\bin\material-tools:8:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Thanks in advance!

**Comment by r0b-** [comment]
I use 
`npm.cmd install -g git+https://github.com/angular/material-tools.git#master`
for installation (that succeeds) but still the error :-(

**Comment by crisbeto** [comment]
Why are you installing it from GitHub? Try using `npm install -g angular-material-tools`.

**Comment by r0b-** [comment]
I like to use the extending palettes feature...

**Comment by crisbeto** [comment]
Released a new version that should have it.

**Comment by r0b-** [comment]
Great - Thanks a lot!

**Comment by r0b-** [comment]
ok so cli tools are available again but the now I get this error (with palette extending config):
```
[08:52:54]: Error: Missing colors 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, A100, A200, A400, A700 in palette _grey!
    at checkPaletteValid (C:\...\.material-cache\1.1.1\module\angular-material.js:5761:13)
    at Object.definePalette (C:...\.material-cache\1.1.1\module\angular-material.js:5744:22)
    at ThemeBuilder._registerPalette (C:\...\npm\node_modules\angular-material-tools\lib\builders\ThemeBuilder.js:74:34)
    at C:\...\npm\node_modules\angular-material-tools\lib\builders\ThemeBuilder.js:55:81
    at Function.Utils.forEach (C:\...\npm\node_modules\angular-material-tools\lib\common\Utils.js:42:17)
    at ThemeBuilder._buildThemingService (C:\...\npm\node_modules\angular-material-tools\lib\builders\ThemeBuilder.js:55:23)
    at new ThemeBuilder (C:\...\npm\node_modules\angular-material-tools\lib\builders\ThemeBuilder.js:22:14)
    at MaterialTools.MaterialBuilder._buildTheme (C:\...\npm\node_modules\angular-material-tools\lib\builders\MaterialBuilder.js:63:34)
    at C:\...\npm\node_modules\angular-material-tools\lib\MaterialTools.js:121:50
```

It seems the new code is not in the release... can you check again?

Thanks

**Comment by crisbeto** [comment]
Sorry, I hadn't pushed all of the commits properly last time. I've released `v1.0.0-beta.5` that should sort it out. Can you give it another try?

**Comment by r0b-** [comment]
It works now! Thanks again.

One last question: If I include the generated angular-material.js & angular-material.css all the style-tags in the head are still generated. How can I prevent that?

**Comment by r0b-** [comment]
ok got it -` $mdThemingProvider.disableTheming();`
